### ISSUE TITLE
Update to Qt version

### ISSUE THREAD

**Issue by Sinihopea** [flathub/com.kristianduske.TrenchBroom#3]
I'm rising this issue to tell that I'm still here and I still do care about maintaining this. The reason there haven't been any updates is that Trenchbroom has switched to Qt as its underlying GUI toolkit and I've been waiting for it to mature. I will update Flatpak packaged Trenchbroom to Qt version upcoming months.

**Comment by kduske** [comment]
Awesome! If you need any help from our side, let us know.

**Comment by Sinihopea** [comment]
Heh, I actually do have few small things in mind:

- You should take and provide the appdata.xml in Trenchbroom but I'm fine maintaining it just for Flatpak for now. However should there be other package managers which might want to use it... at that point appdata.xml should be provided through Trenchbroom repository to ensure it's the one and same file for all the different distributors.
- Currently appdata.xml I provide is lacking screenshots but since you've added a screenshot to the webpage I'm going to be using that if that's ok. I can then close the other issue with that change. It would be nice if there was more than one screenshot available.
- I'm going to tighten the access rights of Trenchbroom Flatpak version to user's home directory and do some other fine tuning. If I encounter errors I might contact you to ask about them but I don't think that will be necessary just yet.
- It would be great if there was a switch for not compiling the documentation / if there was no dependency to pandoc in Trenchbroom since pandoc is causing tiny bit of trouble due the fact that I cannot compile it. Compiling pandoc currently requires bootstrapping Haskell compiler and there is no reasonable way for me to do that so I have to use pre-build Pandoc x86_64 binaries to get Trenchbroom itself compiled. Or something like that IIRC. EDIT: I should add that this is primary reason why Trenchbroom Flatpak isn't available for ARM CPUs as well even thought apparently (I heard) TB works on ARM chips just fine.

**Comment by kkga** [comment]
hey @Sinihopea, are you still blocked on updating the flatpak to latest 2020.1 release?

**Comment by Sinihopea** [comment]
@kkga Yes. I started working on it but it turns out that on my Fedora 32 Workstation system I cannot test it. I'm running into trouble where the compilation segfaults or the produced binaries are garbage and don't work. In theory everything should work if I pushed the updated json file out but I don't dare to do it before I've tested it. I'll try on another PC later this upcoming weekend.

The troubling thing is that I don't know what causes this. We're suspecting that it might be a CPU issue since I have AMD Ryzen 9 3900X with X570 chipset running underneath. There have been similar problems with GCC and Clang with Ryzen CPUs in past according to Google search results. But it doesn't explain why things work perfectly fine when I compile the Trenchbroom inside a Fedora 32 virtual machine. Backtraces point out to a piece of code in vecmath library TB uses but when similar piece of code is tested out in a simple program it works as intended.

**Comment by Sinihopea** [comment]
Well, I've been trying to get this built for a week now without much success. There has to be something I don't know or understand about packaging Qt applications with Flatpak. However I'm doing things exactly like most KDE applications do it and I don't know why things fail.

I even formatted my Intel based laptop and installed Ubuntu 20.04 there to just try building it in a different distribution from Fedora 32 Workstation. And my attempts to compile v2020.1 release of Trenchbroom for Flatpak usually crashes at when parsing through shortcuts.js and dump-shortcuts dumps core like on Fedora. Also some tests fail with Q_QPA_PLATFORM=xcb cannot be loaded due unknown reasons. And finally Pandoc has been again a source of pain but I was able to fix its issues.

I'm able to compile a working Trenchbroom v2020.1 dpkg package outside the Flatpak environment. So I'm not going to give up yet but I might need help from @kduske and co. to get this done.

**Comment by kkga** [comment]
> And my attempts to compile v2020.1 release of Trenchbroom for Flatpak usually crashes at when parsing through shortcuts.js and dump-shortcuts dumps core like on Fedora.

I've been trying to compile v2020.1 on Solus and also getting the same errors with shortcuts.js and dump-shortcuts.

**Comment by 1player** [comment]
It would be great to have a branch for the broken Qt version, so other people could test and see whether they can reproduce the errors. 

I managed to track down @Sinihopea patched JSON build file  (https://gist.github.com/Sinihopea/058957ebed1916abb865316224e51edb) from the upstream bug — which should be linked to this issue: https://github.com/TrenchBroom/TrenchBroom/issues/3320 — but doesn't seem to be building pandoc correctly so I can't test whether it works on my Intel machine.

Let's create a branch so we can all figure out what's going on.

**Comment by Sinihopea** [comment]
> It would be great to have a branch for the broken Qt version, so other people could test and see whether they can reproduce the errors.
> 
> I managed to track down @Sinihopea patched JSON build file (https://gist.github.com/Sinihopea/058957ebed1916abb865316224e51edb) from the upstream bug — which should be linked to this issue: [TrenchBroom/TrenchBroom#3320](https://github.com/TrenchBroom/TrenchBroom/issues/3320) — but doesn't seem to be building pandoc correctly so I can't test whether it works on my Intel machine.
> 
> Let's create a branch so we can all figure out what's going on.

You cannot build Pandoc because it has been written in Haskell and we... or at least all the Flatpak projects one year ago I looked at weren't able to bootstrap Haskell compiler. What they do is download the pre-built binaries from the Pandoc website. There is however a new possibility of not building documentation for Trenchbroom now in Qt port by supplying parameter to CMake which enables us to drop the Pandoc out of the package and skip the BS. But I haven't had a moment to test it yet and IIRC it was undocumented when I saw it.

And I agree that it would probably make a lot of sense to have a public branch for the Qt version. I'll try to get mine here.

**Comment by Sinihopea** [comment]
Just a heads up. I just managed to build the Qt TB 2020.1 release Flatpak package using my laptop instead of the workstation. I'll try to find time tomorrow to get the changes pushed here and see that it gets built.

**Comment by Sinihopea** [comment]
One more thing before I head to bed. I managed to build 2020.2 as well. I'll skip 2020.1 and move to supporting 2020.2 straight.

**Comment by Sinihopea** [comment]
Ok, initial build of 2020.2 has passed the Flathub checks. It still does require some work but this should get this release up and running for people. Please, feel free to suggest improvements. I want to learn to become a better maintainer. I understand that it has been a while since the last Flatpak release but with the Trenchbroom Qt port now out there updates should become more regular.

**Comment by kduske** [comment]
This is great news, thank you! Regarding pandoc, I know it's a pain in the butt for you, but I haven't found a good alternative to it yet. We also download and install pandoc as part of our builds using a package manager.

Regarding not building the manual I'd be very disappointed if that happens. The manual has been a lot of work and it is an important part of the software.
